services:
  nats:
    image: nats:2.10.22
    ports:
      - "127.0.0.1:4222:4222"  # Client connections
      - "127.0.0.1:8222:8222"  # HTTP management
      - "127.0.0.1:6222:6222"  # Clustering
    environment:
      - NATS_SERVER_NAME=nats-server
      - NATS_CLUSTER_NAME=trading-cluster
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - trading-network
    depends_on:
      - influxdb

  jetstream:
    image: nats:2.10.22
    ports:
      - "127.0.0.1:4223:4222"  # Client connections
      - "127.0.0.1:8223:8222"  # HTTP management
    environment:
      - NATS_SERVER_NAME=jetstream-server
      - NATS_CLUSTER_NAME=breakout-cluster
    command:
      - --jetstream

volumes:
  nats-data:
  nats-config:

networks:
  trading-network:
    driver: bridge