services:
  nats:
    image: nats:2.10.22
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
      - "127.0.0.1:6222:6222"
    environment:
      - NATS_SERVER_NAME=nats-server
      - NATS_CLUSTER_NAME=trading-cluster
    command:
      - --jetstream
    networks:
      - trading-network
    depends_on:
      - influxdb