services:
  nats:
    image: nats:latest
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:8222:8222"
      - "127.0.0.1:6222:6222"
    # volumes:
    #   - nats-data:/data
    environment:
      - NATS_SERVER_NAME=nats-server
      - NATS_CLUSTER_NAME=trading-cluster
    networks:
      - trading-network
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    networks:
      - trading-network
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=trading-org
      - DOCKER_INFLUXDB_INIT_BUCKET=trading_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
    # volumes:
    #   - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ../visualization/provisioning:/etc/grafana/provisioning
      - ../visualization/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - trading-network
  

# volumes:
#   nats-data:
#     driver: local
#   influxdb-data:
#     driver: local

networks:
  trading-network:
    driver: bridge