services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    networks:
      - trading-network
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=trading-org
      - DOCKER_INFLUXDB_INIT_BUCKET=trading_bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      # Memory optimization settings
      # Inform the kernel that InfluxDB intends to page in mmap’d sections of TSM files.
      - INFLUXD_STORAGE_TSM_USE_CACHE=true
      # Maximum size (in bytes) a shard’s cache can reach before it starts rejecting writes.
      - INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE=4g
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 2G
          cpus: '2'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ../visualization/provisioning:/etc/grafana/provisioning
      - ../visualization/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - trading-network
  
networks:
  trading-network:
    driver: bridge
